services:
  api:
    build: ./
    container_name: medods
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.21.1
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations

  db:
    image: postgres:latest
    container_name: medodsdb
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  migrations:
